<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">

	<title>grid </title>
	<meta name="viewport" content="with=device-width,initial-scale-1">
	<link rel="stylesheet" href="./bootstrap-3.3.5-dist/css/bootstrap.min.css" type="text/css" media="screen" charset="utf-8">
	<style type="text/css" media="screen">
		.row{ 
			margin-bottom: 20px;
		} 
		.row .row{
			margin-top: 10px;
			margin-bottom: 0;
		}
		[class*="col-"]{
			padding-top: 15px;
			padding-bottom: 15px;
			background-color: #eee;
			background-color: rgba(86,61,124,15);
			border: 1px solid #ddd;
			border: 1px solid rgba(86,61,124,2);
		}
</style>
	
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-1"> col-md-1 </div>
			<div class="col-md-1"> col-md-1 </div>
			<div class="col-md-1"> col-md-1 </div>
			<div class="col-md-1"> col-md-1 </div>
			<div class="col-md-1"> col-md-1 </div>
			<div class="col-md-1"> col-md-1 </div>
			<div class="col-md-1"> col-md-1 </div>
			<div class="col-md-1"> col-md-1 </div>
			<div class="col-md-1"> col-md-1 </div>
			<div class="col-md-1"> col-md-1 </div>
			<div class="col-md-1"> col-md-1 </div>
			<div class="col-md-1"> col-md-1 </div>
		</div>

	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-3"> col-md-3 </div>
			<div class="col-md-3"> col-md-3 </div>
			<div class="col-md-3"> col-md-3 </div>
			<div class="col-md-3"> col-md-3 </div>
		</div>

		<div class="row">
			<div class="col-md-3"> col-md-3  col-md-3  col-md-3  col-md-3  col-md-3  col-md-3  col-md-3  col-md-3  col-md-3  col-md-3 </div>
			<div class="col-md-3"> col-md-3 </div>
			<div class="col-md-3"> col-md-3 </div>
		</div>
		<div class="row">
			<div class="col-md-4 col-md-offset-1">
				col-md-4 col-md-offset-1
			</div>
		</div>

		<div class="row">
			<div class="col-md-9">
				one
				<div class="row">
					<div class="col-xs-8">
						first test col-xs-8
					</div>
					<div class="col-xs-4">
						first test col-xs-4
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-9 col-md-push-3">
				col-md-9 col-md-push-3
			</div>
			<div class="col-md-3 col-md-pull-9">
				col-md-3 col-md-pull-9
			</div>
		</div>
	</div>
</body>
</html>
