#|(write (atom 'abcd))
(terpri)
(write (equal 'a 'b))
(terpri)
(write (evenp 10))
(terpri)
(write (evenp 9))
(terpri)
(write (oddp 7))
(terpri)
(write (zerop 0.0000000001))
(terpri)
(write (eq 3 3.0))
(terpri)
(write (equal 3 3.0)
(terpri)
(write (null nil))|#

(terpri)
(defun hahha (num)
	(cond ((zerop num) 1)
	 (t (* num (hahha (- num 1))))))
(setq k 15)
(format t "~% hahha ~d is: ~d" k (hahha k))

