(setq x 10)
(setq y 34.689798)
(setq ch nil)
(setq n 1289.78)
(setq bg 11.0e+4)	
(setq r 124/2)
(print x)
(print y)
(print n)
(print ch)
(print bg)
(print r)

(print (type-of x))
(print (type-of y))
(print (type-of ch))
(print (type-of n))
(print (type-of bg))
(print (type-of r))
