version: '3'
services:
    web:
        image: "nginx:latest"
        volumes:
            - "./sme:/sme"
            - "./sme.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8080:80"
        networks:
            - "sme-network"
    php:
        image: "php:fpm"
        ports:
            - "9000:9000"
        volumes:
            - "./sme:/sme"
        networks:
            - "sme-network"
networks:
    sme-network:
        driver: "bridge"
