* 凯恩斯三大基本理论：
** 1、边际消费倾向递减规律
*** 实际消费支出和实际收入之间有稳定的函数关系，边际消费倾向是正数，但小于一。随着收入的增加，消费并不按相同的比例增加，其差额就是储蓄。收入愈增加，消费在收入中的比重就愈小，储蓄越大。
*** 是指消费支出增减额对收入增减额的比率。即： MPC=消费增减额/收入增减额
*** 宏观见解
***** ①在人们收入增加的时候，消费也随之增加，但消费增加的比例不如收入增加的比例大。在收入减少的时候，消费也随之减少，但也不如收入减少的那么厉害。富人的边际消费倾向通常低于穷人的边际消费倾向。这是因为穷人的消费是最基本的消费，穷人之所以穷，是因为在穷人的收入中基本生活资料占了相当大的比重，而富人之所以富，在于富人早已超越了基本需求层次，基本生活资料在其收入中所占比例不大。
***** ②边际消费倾向取决于收入的性质。消费者很大程度上都着眼于长期收入前景来选择他们的消费水平。长期前景被称为永久性收入或生命周期收入，它指的是个人在好的或坏的年景下平均得到的收入水平。如果收入的变动是暂时的，那么，收入增加的相当部分就会被储藏起来。收入不稳定的个人通常具有较低的边际消费倾向。
***** ③人们对未来收入的预期对边际消费倾向影响甚大。边际消费倾向的降低，使得萧条更为萧条。
** 2、资本边际效率递减规律
***** 资本的边际效率是使得预期收益现值之和等于资本品价格的贴现率，它反映了厂商增加投资的预期利润率。资本的边际效率递减意味着厂商增加投资时预期利润率递减。凯恩斯认为，投资需求取决于资本边际效率与利率的对比关系。对应于既定的利息率，只有当资本边际效率高于这一利息率时才会有投资。但是，在凯恩斯看来，由于资本边际效率在长期中是递减的，除非利息率可以足够低，否则会导致经济社会中投资需求不足。
** 3、流动偏好规律 
***** 流动偏好（又称“流动性偏好”或“灵活偏好”），是指由于货币具有使用上的灵活性，人们宁肯以牺牲利息收入而储存不生息的货币来保持财富的心里倾向
** 结论： 
***** 市场中不存在一个能把私人利益转化为社会利益的看不见的手，经济危机和失业不可能消除，只有依靠看得见的手即政府对经济的全面干预，才能摆脱经济萧条和失业问题
** 经济效应
*** 内卷化效应
***** 内卷化效应就是长期从事一项相同的工作，并且保持在一定的层面，没有任何变化和改观。这种行为通常是一种自我懈怠，自我消耗。
***** 无论是社会组织还是个人，进入内卷化状态，根本原因就在于精神状态和思想观念。人们常说，信心决定命运，观念决定出路。一个人如果总是自怨自艾，不思改变，不求进取，不谋开拓，民无信心，军无斗志，只能是原地不动，还有可能倒退。总是因陋就简，循规蹈矩，按部就班，只能进入周而复始的轮回状态。两千年的小农意识，生产的只能是两千年的自然经济，不可能产生出市场经济和现代经济。
*** 马太效应
***** 强者愈强、弱者愈弱。
***** 缺陷： 只看到事物发展的短期趋势，只反映了数量方面的变化，忽视了性质的变化，不能用于分析事物发展的长期趋势；事实上，在客观世界，任何事物都遵循发生-发展-成熟-衰老-灭亡的规律，没有什么是永远不变的。
** 墓志铭
***** 不用为我悲哀，朋友，千万不要为我哭泣。
***** 因为，往后我将永远不必再辛劳。
***** 天堂里将响彻赞美诗与甜美的音乐，
***** 而我甚至也不再去歌唱。
