*  《失控》-- 全人类的最终命运和结局？
*** 自我能动
     + 有机体既是它自己的因也是它自己的果，既是它自己固有的秩序和组织的因，也是其固有秩序和组织的果。
     + 每一个 *自我* 都是一个同义反复：自明、自指、以自己为中心并且自己创造自己。
     + 一个 *系统* ，就是任何一种能够自说自话的东西。
     + 自动控制三个阶段
       - 由蒸汽机所引发的能量控制的第一阶段
       - 对物质的精确控制是第二阶段
       - 对信息本身的控制是第三阶段
     + 21 世纪的核心事件，是对 *信息的颠覆* 。
     + 自动化的历史，就是一条 *从人类控制到自动控制* 的单向通道。其结果就是从人类的自我到第二类自我的不可逆转的转移。而第二类自我是在我们控制之外的，是失控的。
     + 具有自我适应能力、像自己的目标进化、不受人类监管自行成长的机器，将会是下一个巨大的技术进步。要想获得有智能的控制，唯一的办法就是给机器自由。
     + 有些事必须先做，而且要按 *正确的次序* 去做。
     + *复杂的机器必定是逐步地，而且往往是间接地完善的。别指望通过一次华丽的组装就能完成整个工作正常的机械系统。你必须首先制作一个可运行的系统，再以此为平台研制你真正想完成的系统* (精辟呀!微信,Facebook也是一步步来的)。
*** 密封的瓶装生命
     + 一天就可以摧毁的东西，要想建成它，可能会需要几年甚至几个世纪的时间。
     + 复杂性的开端根植于混沌之中。不过，如果复杂系统能够在一段时间的互相迁就之后获得共同的 *平衡* ，那么之后就再没有什么能够让它脱离轨道了。(是不是和习惯一样？一旦养成了自己固定的生活习惯，思维习惯，就会潜意识地贯彻下去。)
     + “封闭”意味着与流动隔绝。一个真正的封闭系统，是不会参与外部元素流动的; 换句话，它所有的循环都是自治的。
     + “系统”意味着相互 *连通* 。系统中的事物是相互纠结的，直接或者间接地连接到一个共同的命运。
     + *“存活”意味着惊喜* 。
     + 静态才是生态球的常态。
     + 生态球按比例放大后仍很完好。生态球越大，达到稳定所需时间就越长，破坏它也就越困难。只要处于正常状态，一个活系统的集体代谢过程就会扎下根，然后一直持续下去。
*** 生态技术玻璃球
     + 生命经营的事业就是改造环境使其有益于生命。如果你能把生命聚拢成为一个群落，给它们充分的自由制造自己茁壮成长所需的条件，这个生物集合体就能一直生存下去，也没有必要知道它是怎样运转的。
     + 对于任何一个复杂、危险的项目来说，最理想的团队人数是８个人。超过８个人，会造成决策缓慢和耽搁；而少于８个人，突发事件或者疏忽大意就会变成严重的阻碍。
     + 细节是至关重要的东西。
     + 生命的任何领域都是由数不清的独立的回路编织而成的。
***  合成生态系统
     + 一旦你改变了生态系统，　并找到适合播种的的种子，以及必不可少的气候窗口，改变就开始了，而且这是不可逆转的。这个合成的生态系统持续运转下去并不需要人的存在，它不受干扰仍会保持下去。
     + 创造生物圈：
       - 微生物做绝大部分的工作
       - 土壤是有机体, 它是活的。它会呼吸。
       - 创造【冗余】的食物网络
       - 逐步地增加多样性
       - 如果不能提供一种物理功能，就需要模拟一个类似的功能
       - 大气会传达整个系统的状态
       - 聆听系统，看看它要去哪里
     + 所有的封闭系统都是会被打开的，至少会出现泄露。(也就是: 不存在绝对封闭系统)
