** 《如何读懂音乐》--听音乐!=懂音乐
*** 听前准备
    + 对具有高度潜在理解力的听众有一个起码的要求: 当他听到一个旋律时，必须能把它识别出来。
    + 善于模仿的人还不能算是演员，对音乐有很强模仿力的人也不一定意味着音乐才能出色。
    + 光聆听音乐还不够，还必须能把特定时刻听到的音乐与在不久前刚刚听到的和即将听到的音乐联系起来。 *音乐是一种时间的艺术* 。
    + 三个层次
      - 感官层次
      - 表达层次
      - 纯音乐层次
*** 怎么听音乐
    + 音乐的感染力是一种强大而原始的力量。
    + 并非所有的作曲家在处理声音方面都用同一种方法。不要以为音乐的价值等同于它诉诸感官的程度，就音响方面而言，也不要以为最优美的音乐都是由最伟大的作曲家写的。
    + 凡事不能走极端。
    + 所有的音乐都有表达能力，有的强些有的弱些，所有的音符背后都有某种意义，毕竟这音符背后的意义构成了作品想要言说，以及作品所关涉的内容。
    + 音乐在不同的时刻有不同的表达: 或安详安静或朝气蓬勃; 或懊悔不迭或心满意足; 或暴怒或喜悦。它可以用无数细微差别和变化来表达上述情绪中的一种，以及许多其他的情绪，甚至可以表达任何语言都无法言说的情绪。
    + 专业音乐人士和业余爱好者的区别在于他们更关注音符本身。
    + 所有人都应该在纯音乐的层次上使自己更敏感, 这点非常重要。
    + 毕竟他们使用的是实际的音乐素材。理解能力强的听众必须强化对音乐素材的意识，知道它们是怎么发展推进的; 必须更有意识地去听音乐的旋律、节奏、和声和音色。为了跟上作曲家的思想脉络，必须懂得一些音乐曲式的原理，这一点尤其重要。当你能听出旋律、节奏等要素的时候，你慢慢就会在纯音乐的层次上听出门道。 + 从某种意义上说，理想的听众在同一时刻既能进入音乐也能超脱音乐，既可以品评音乐也可以欣赏音乐; 希望音乐向某个方面运行，同时又注视着它向另外一个方向进行，几乎像作曲家创作时一样。原因在于，作曲家在创作的时候必须能进能出，时而心醉沉迷，时而冷静批评。无论创作还是欣赏音乐，同时要具有主客观两种态度。
    + 只有当你更自觉、更有意识地听; 不仅是听，而且带着某些目的地听，才能加深对音乐的理解。
*** 音乐创作过程
    + 灵感－－　乐思。
    + 作曲家的任务是要使听音乐的人始终知道自己听到了哪个段落，开始段、中间段，还是结束段。
    + 音乐必须永远是流动的，这是它的本质, 而这种连续性和流动性, 也就是那条“长线”的创造，是决定每个作曲家成败的关键。
*** 音乐的四种要素
    + 音乐有四中基本要素: 节奏、旋律、和声和音色。
    + 音乐和诗的区别在于，音乐可以同时具有明显的节拍感和节奏感。
    + 在时值上，一个全音符等于两个二分音符，或者四个四分音符，或者八个八分音符，以此类推。
    + 一个全音符的时值只是相对的，但是由它分割而成的较小的时值都是均等的。如果每个小节有四个四分音符，这首乐曲就是四四拍。
    + 只有当强拍不重合的时候，才会出现真正意义上的复节奏。
    + 从整体上说，一段优美的旋律就像一首乐曲，在比例规模等方面应当让人满意，必须让人感到它是完备的，非如此不可。为了达到这个目的，旋律线一定要悠长而流畅，有令人愉悦的高低起伏，通常在接近尾声时达到高潮。在旋律结构中，节奏的流畅感也非常重要。旋律必须能引起听众的情感反应。(最近听过一个唱歌节目，唱的人自己哭到泪流满面，而听众都是面目表情!)
    + "1234567(do lei mi fa so la xi do)" 叫做自然大调音阶(七声音阶)。
