<h2>Sign using this form</h2>

<?php echo $this->tag->form('signup/register') ?>

	<p>
		<label for="name">Name</label>
		<?php echo $this->tag->textField("name") ?>
	</p>

	<p>
		<label for="name">E-Mail</label>
		<?php echo $this->tag->textField("email") ?>
	</p>

	<p>
		<?php echo $this->tag->submitButton("Register") ?>
	</p>

</form>

<?php use Phalcon\Tag; ?>
<h2> Sign using this form </h2>
<?php
echo Tag::form("signup/register");
?>
<p>
<label for="name">Name</label>
<?php echo Tag::textField("name"); ?>
</p>

<p>
<label for="name">E-mail</label>
<?php echo Tag::textField("email"); ?>
</p>
<p>
<?php echo Tag::submitButton("Register"); ?>
</p>
